### PR TITLE
Fixed a typo in mcmod.info that has been nagging me for way too long.

### PR DESCRIPTION
**Pull request by freedownloadhere**
I have cloned this repo endless times at this point and every time I see that typo it makes me lose faith in humanity :grin:

### CODE REVIEW

**Comment by nea89o** [comment]
Nah my way of writing it is more rad 😎

**Comment by nea89o** [comment]
(im sorry i dont mean to be rude)

**Comment by freedownloadhere** [comment]
oh I didnt know it was intentional lmao alright best wishes

**Comment by nea89o** [comment]
Eh it's all placeholder anyway. In the future the dream is to have an interactive script of some sorts to generate everything and prefill all the values. Sadly have yet to find a way to make that user friendly. (Maybe it is time to invent a template format standard and then write an intellij plugin for it)

**Pull request closed without merging**
